# Generated by Django 4.1 on 2022-10-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_rename_activites_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roomtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type_name', models.CharField(max_length=100)),
                ('noof_beds', models.CharField(max_length=10)),
                ('max_occupancy', models.CharField(max_length=10)),
                ('noof_rooms', models.CharField(max_length=10)),
                ('picture', models.FileField(default=None, null=True, upload_to='roomtype')),
                ('rental_description', models.TextField(max_length=1000)),
            ],
            options={
                'db_table': 'room_type',
            },
        ),
    ]
