# Generated by Django 4.1 on 2022-10-11 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_roomtype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Roomtype',
            new_name='Rentaltype',
        ),
        migrations.AlterModelTable(
            name='rentaltype',
            table='rental_type',
        ),
    ]
