# Generated by Django 4.1 on 2022-10-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0007_rentaltype_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentaltype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='rentaltype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
