# Generated by Django 4.1 on 2022-10-13 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0009_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxtype_name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tax_type',
            },
        ),
        migrations.AddField(
            model_name='tax',
            name='tax_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rentals.taxtype'),
            preserve_default=False,
        ),
    ]
