# Generated by Django 4.1 on 2022-10-13 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0012_ratetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_name', models.CharField(max_length=100)),
                ('included_occupants', models.CharField(max_length=100)),
                ('extra_adult_charge', models.CharField(max_length=100)),
                ('extra_children_charge', models.CharField(max_length=100)),
                ('weekend_surcharge', models.CharField(max_length=100)),
                ('channel_manager_markup', models.CharField(max_length=100)),
                ('disable_rates', models.BooleanField(default=b'I00\n')),
                ('description', models.TextField(max_length=1000)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.ratetype')),
            ],
            options={
                'db_table': 'rate',
            },
        ),
    ]
