# Generated by Django 4.1 on 2022-10-13 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0013_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='channel_manager_markup',
        ),
    ]
