# Generated by Django 4.1 on 2022-10-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0017_rename_guest_name_bookings_email_bookings_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='check_in',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='check_out',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
