# Generated by Django 4.1 on 2022-10-17 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0018_alter_bookings_check_in_alter_bookings_check_out_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='updated_at',
        ),
    ]
