# Generated by Django 4.1 on 2022-10-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0019_remove_bookings_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='check_in',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='check_out',
            field=models.DateTimeField(),
        ),
    ]
