# Generated by Django 4.1 on 2022-10-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0021_discounttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='discounttype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='discounttype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
