# Generated by Django 4.1 on 2022-10-17 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0022_discounttype_created_at_discounttype_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discounts_name', models.CharField(max_length=100)),
                ('discounts_amount', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.discounttype')),
            ],
            options={
                'db_table': 'discount',
            },
        ),
    ]
