# Generated by Django 4.1 on 2022-10-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0025_rental_created_at_rental_status_rental_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='policy',
        ),
        migrations.AddField(
            model_name='rental',
            name='policy',
            field=models.ManyToManyField(to='rentals.policy'),
        ),
    ]
