# Generated by Django 4.1 on 2022-10-18 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0026_remove_rental_policy_rental_policy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='policy',
        ),
        migrations.AddField(
            model_name='rental',
            name='activities',
            field=models.ManyToManyField(to='rentals.activity'),
        ),
        migrations.AddField(
            model_name='rental',
            name='amenities',
            field=models.ManyToManyField(to='rentals.amenities'),
        ),
        migrations.AddField(
            model_name='rental',
            name='policy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rentals.policy'),
            preserve_default=False,
        ),
    ]
