# Generated by Django 4.1 on 2022-10-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0029_invoice_invoiceitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_logo', models.ImageField(upload_to='company')),
                ('company_email', models.CharField(blank=True, max_length=100, null=True)),
                ('company_tel', models.CharField(max_length=15)),
                ('company_address', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'company_profile',
            },
        ),
    ]
