# Generated by Django 4.1 on 2022-10-31 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0032_amenities_user_id_bookings_user_id_channel_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='user_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ratetype',
            name='user_id',
            field=models.IntegerField(default=1),
        ),
    ]
