# Generated by Django 4.1 on 2022-11-01 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0034_remove_rental_activities_remove_rental_amenities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalAmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('amenities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.amenities')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.rental')),
            ],
            options={
                'db_table': 'rental_amenities',
            },
        ),
    ]
