# Generated by Django 4.1 on 2022-11-01 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0036_rentalsgallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.policy')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.rental')),
            ],
            options={
                'db_table': 'rental_policy',
            },
        ),
        migrations.CreateModel(
            name='RentalActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('activities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.activity')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.rental')),
            ],
            options={
                'db_table': 'rental_activities',
            },
        ),
    ]
