# Generated by Django 4.1 on 2022-11-02 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0037_rentalpolicy_rentalactivities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalamenities',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='rentalamenities',
            name='rental',
        ),
        migrations.RemoveField(
            model_name='rentalpolicy',
            name='policy',
        ),
        migrations.RemoveField(
            model_name='rentalpolicy',
            name='rental',
        ),
        migrations.DeleteModel(
            name='RentalActivities',
        ),
        migrations.DeleteModel(
            name='RentalAmenities',
        ),
        migrations.DeleteModel(
            name='RentalPolicy',
        ),
    ]
