# Generated by Django 4.1 on 2022-11-15 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0040_attributes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturingYM',
            fields=[
                ('ManufacturingYMID', models.AutoField(primary_key=True, serialize=False)),
                ('ManufacturingDate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'manifacturing',
            },
        ),
        migrations.AddField(
            model_name='bookings',
            name='mfdate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rentals.manufacturingym', verbose_name='Manufacturing Date'),
        ),
    ]
