# Generated by Django 4.1 on 2022-11-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0041_manufacturingym_bookings_mfdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='mfdate',
        ),
        migrations.AddField(
            model_name='bookings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name='ManufacturingYM',
        ),
    ]
