# Generated by Django 4.1 on 2022-11-15 17:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0042_remove_bookings_mfdate_bookings_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
