# Generated by Django 4.1 on 2022-12-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0045_remove_rentalsgallery_rental'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalsgallery',
            name='rental',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
