# Generated by Django 4.1 on 2022-12-08 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0047_rename_rental_rentalsgallery_rental_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalsgallery',
            name='rental_id',
        ),
        migrations.AddField(
            model_name='rentalsgallery',
            name='rental',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rentals.rental'),
            preserve_default=False,
        ),
    ]
