# Generated by Django 4.1 on 2022-12-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0048_remove_rentalsgallery_rental_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalsgallery',
            name='rental',
            field=models.IntegerField(),
        ),
    ]
