# Generated by Django 4.1 on 2022-12-08 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0049_alter_rentalsgallery_rental'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalsgallery',
            old_name='rental',
            new_name='rental_id',
        ),
    ]
