# Generated by Django 4.1 on 2022-12-09 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0051_category_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='channel_description',
        ),
    ]
