# Generated by Django 4.1 on 2022-12-13 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0054_channelmanagement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelmanagement',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='channelmanagement',
            name='status',
        ),
        migrations.RemoveField(
            model_name='channelmanagement',
            name='updated_at',
        ),
    ]
