# Generated by Django 4.1 on 2022-12-26 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0058_remove_invoice_user_id_remove_invoiceitem_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='rentaltype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rentals.rentaltype'),
            preserve_default=False,
        ),
    ]
