# Generated by Django 4.1 on 2022-12-26 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0059_rental_rentaltype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='rentaltype',
        ),
    ]
