# Generated by Django 4.1 on 2022-12-26 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0060_remove_rental_rentaltype'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='rental_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rentals.rentaltype'),
            preserve_default=False,
        ),
    ]
