# Generated by Django 4.1 on 2022-12-26 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0061_rental_rental_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='user_id',
        ),
    ]
