# Generated by Django 4.1 on 2022-12-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0065_country_propertyrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='attributes',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='rentaltype',
            name='user_id',
        ),
        migrations.AddField(
            model_name='invoice',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
