# Generated by Django 4.1 on 2022-12-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0068_alter_partner_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='tenure',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
