# Generated by Django 4.1 on 2022-12-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0073_alter_subscriptionplan_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='rental_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rate',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
