# Generated by Django 4.1 on 2023-01-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0075_room_roomtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='icon',
            field=models.FileField(default=None, null=True, upload_to='room'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='icon',
            field=models.FileField(default=None, null=True, upload_to='roomtype'),
        ),
    ]
