# Generated by Django 4.1 on 2023-01-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0076_room_icon_roomtype_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentalsgallery',
            options={'ordering': ('position',)},
        ),
        migrations.AddField(
            model_name='rentalsgallery',
            name='position',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
