# Generated by Django 4.1 on 2023-01-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0077_alter_rentalsgallery_options_rentalsgallery_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='activities_id',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='amenities_id',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='policy_id',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='rental_logo',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='rental_type',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='rental_url',
        ),
        migrations.AddField(
            model_name='rental',
            name='rental_short_description',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rental',
            name='rental_description',
            field=models.TextField(max_length=3000),
        ),
    ]
