# Generated by Django 4.1 on 2023-01-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0079_rentalbasic'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=1000)),
                ('apartment', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('rental_id', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'rental_location',
            },
        ),
    ]
