# Generated by Django 4.1 on 2023-01-04 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0081_amenities_rental_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenities',
            name='rental_id',
        ),
    ]
