# Generated by Django 4.1 on 2023-01-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0082_remove_amenities_rental_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalamenities',
            name='rental',
        ),
        migrations.AddField(
            model_name='rentalamenities',
            name='rental_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalamenities',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='rentalamenities',
            name='amenities',
            field=models.CharField(max_length=500),
        ),
    ]
