# Generated by Django 4.1 on 2023-01-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0083_remove_rentalamenities_rental_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarlyBirdDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_less', models.CharField(max_length=100)),
                ('booking_less_discount', models.CharField(max_length=100)),
                ('booking_more', models.CharField(max_length=100)),
                ('booking_more_discount', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('user_id', models.IntegerField()),
                ('rental_id', models.IntegerField()),
            ],
            options={
                'db_table': 'earlybird_discount',
            },
        ),
        migrations.CreateModel(
            name='LongStayDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seven_nights', models.CharField(max_length=100)),
                ('fourteen_nights', models.CharField(max_length=100)),
                ('twenty_one_nights', models.CharField(max_length=100)),
                ('twenty_eight_nights', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('user_id', models.IntegerField()),
                ('rental_id', models.IntegerField()),
            ],
            options={
                'db_table': 'longstay_discount',
            },
        ),
    ]
