# Generated by Django 4.1 on 2023-01-05 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0089_room_room_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bed',
            table='bed',
        ),
        migrations.AlterModelTable(
            name='room',
            table='rooms',
        ),
    ]
