# Generated by Django 4.1 on 2023-01-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0090_alter_bed_table_alter_room_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=100)),
                ('basic_night', models.CharField(max_length=100)),
                ('weekend_night', models.CharField(max_length=100)),
                ('guest_number', models.CharField(max_length=100)),
                ('minimum_stay', models.CharField(max_length=100)),
                ('maximum_stay', models.CharField(max_length=3000)),
                ('status', models.BooleanField(default=True)),
                ('user_id', models.IntegerField()),
                ('rental_id', models.IntegerField()),
            ],
            options={
                'db_table': 'rental_basic_rates',
            },
        ),
        migrations.CreateModel(
            name='SeasonalRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_name', models.CharField(max_length=100)),
                ('start_date', models.CharField(max_length=100)),
                ('end_date', models.CharField(max_length=100)),
                ('basic_night', models.CharField(max_length=100)),
                ('weekend_night', models.CharField(max_length=100)),
                ('minimum_stay', models.CharField(max_length=3000)),
                ('maximum_stay', models.CharField(max_length=3000)),
                ('status', models.BooleanField(default=True)),
                ('user_id', models.IntegerField()),
                ('rental_id', models.IntegerField()),
            ],
            options={
                'db_table': 'rental_seasonal_rates',
            },
        ),
    ]
