# Generated by Django 4.1 on 2023-01-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0091_basicrates_seasonalrates'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalCleaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaning_available', models.CharField(max_length=100)),
                ('cleaning_basis', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('rental_id', models.IntegerField()),
            ],
            options={
                'db_table': 'rental_cleaning',
            },
        ),
        migrations.CreateModel(
            name='RentalDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_deposit', models.BooleanField()),
                ('amount', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('rental_id', models.IntegerField()),
            ],
            options={
                'db_table': 'rental_deposit',
            },
        ),
    ]
