# Generated by Django 4.1 on 2023-01-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0092_rentalcleaning_rentaldeposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentaldeposit',
            name='security_deposit',
            field=models.CharField(max_length=100),
        ),
    ]
