# Generated by Django 4.1 on 2023-01-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0095_extraservices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraservices',
            name='earliest_guest_order',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extraservices',
            name='fee_basis',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extraservices',
            name='guest_cancel_order',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extraservices',
            name='latest_guest_order',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extraservices',
            name='service_price',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
