# Generated by Django 4.1 on 2023-01-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0096_alter_extraservices_earliest_guest_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_service_name', models.CharField(max_length=100)),
                ('custom_service_provided', models.CharField(max_length=100)),
                ('custom_fee_basis', models.CharField(max_length=100, null=True)),
                ('custom_service_price', models.CharField(max_length=100, null=True)),
                ('custom_earliest_guest_order', models.CharField(max_length=100, null=True)),
                ('custom_latest_guest_order', models.CharField(max_length=100, null=True)),
                ('custom_guest_cancel_order', models.CharField(max_length=100, null=True)),
                ('custom_extra_message', models.TextField(max_length=3000)),
                ('status', models.BooleanField(default=True)),
                ('user_id', models.IntegerField()),
                ('rental_id', models.IntegerField()),
            ],
            options={
                'db_table': 'rental_custom_extra_services',
            },
        ),
    ]
