# Generated by Django 4.1 on 2023-01-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0097_customservices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_title',
            field=models.CharField(max_length=100),
        ),
    ]
