# Generated by Django 4.1 on 2023-01-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0099_rental_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'other_rooms',
            },
        ),
    ]
