# Generated by Django 4.1 on 2023-01-08 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0100_otherrooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalOtherRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_rooms', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('rental_id', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'rental_other_rooms',
            },
        ),
    ]
