# Generated by Django 4.1 on 2023-01-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0101_rentalotherrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonalrates',
            name='checkin_days',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='seasonalrates',
            name='checkout_days',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
