# Generated by Django 4.1 on 2023-01-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0103_basicrates_checkin_days_basicrates_checkout_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmanagement',
            name='rental_id',
            field=models.IntegerField(default=True),
        ),
    ]
