# Generated by Django 4.1 on 2023-02-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0106_remove_country_code_country_dialing_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_code',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
