# Generated by Django 4.1 on 2023-02-02 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0107_alter_country_country_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalinstruction',
            old_name='country_code',
            new_name='dialing_code',
        ),
    ]
