# Generated by Django 4.1 on 2023-02-02 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0108_rename_country_code_rentalinstruction_dialing_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='dialing_code',
            new_name='code',
        ),
    ]
