# Generated by Django 4.1 on 2023-02-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0109_rename_dialing_code_country_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelmanagement',
            name='channel',
        ),
        migrations.AddField(
            model_name='channelmanagement',
            name='channels',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='channelmanagement',
            table='rental_channel',
        ),
    ]
