# Generated by Django 4.1 on 2023-04-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0111_rentalbed_rentalroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_photo',
            field=models.FileField(default=None, null=True, upload_to='user_profile_photo'),
        ),
    ]
