# Generated by Django 4.1 on 2023-03-09 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingAmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'be_amenities',
            },
        ),
        migrations.CreateModel(
            name='BookingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('image', models.ImageField(default=None, null=True, upload_to='be_rooms')),
                ('no_of_adult', models.CharField(max_length=20)),
                ('no_of_child', models.CharField(max_length=20)),
                ('max_guest', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=100)),
                ('view', models.CharField(max_length=100)),
                ('bed_types', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=200)),
                ('amenities', models.CharField(max_length=500)),
                ('categories', models.CharField(max_length=500)),
                ('tags', models.CharField(max_length=500)),
                ('status', models.BooleanField(default=True)),
                ('user_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'be_rooms',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('status', models.BooleanField(default=True)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'be_categories',
            },
        ),
        migrations.CreateModel(
            name='RoomsGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rooms_gallery')),
                ('user_id', models.IntegerField()),
                ('room_id', models.IntegerField()),
            ],
            options={
                'db_table': 'be_rooms_gallery',
            },
        ),
        migrations.CreateModel(
            name='Seasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.CharField(max_length=100)),
                ('end_date', models.CharField(max_length=100)),
                ('applied_for_days', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'be_seasons',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('periodicity', models.CharField(max_length=200)),
                ('charge', models.CharField(max_length=200)),
                ('featured_image', models.ImageField(upload_to='be_services')),
                ('status', models.BooleanField(default=True)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'be_services',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('status', models.BooleanField(default=True)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'be_tags',
            },
        ),
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price_per_night', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('status', models.BooleanField(default=True)),
                ('user_id', models.IntegerField()),
                ('adults', models.CharField(max_length=100, null=True)),
                ('children', models.CharField(max_length=100, null=True)),
                ('rooms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingengine.bookingroom')),
                ('seasons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingengine.seasons')),
            ],
            options={
                'db_table': 'be_rates',
            },
        ),
    ]
