# Generated by Django 4.1 on 2023-03-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingengine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=200)),
                ('per_adult', models.CharField(max_length=200)),
                ('per_child', models.CharField(max_length=200)),
                ('charge', models.CharField(max_length=200)),
                ('limit', models.CharField(max_length=200)),
                ('include', models.BooleanField(default=True)),
                ('rooms', models.CharField(max_length=2000)),
                ('user_id', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'be_tax',
            },
        ),
    ]
