# Generated by Django 4.1 on 2023-03-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingengine', '0002_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tax',
            name='charge',
        ),
        migrations.AlterField(
            model_name='tax',
            name='amount',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tax',
            name='per_adult',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tax',
            name='per_child',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
