# Generated by Django 4.1 on 2023-03-13 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingengine', '0004_reservation'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reservation',
            table='be_reservation',
        ),
    ]
