# Generated by Django 4.1 on 2023-03-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingengine', '0005_alter_reservation_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rates',
            name='price_per_night',
            field=models.IntegerField(),
        ),
    ]
