# Generated by Django 4.1 on 2023-04-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingengine', '0006_alter_rates_price_per_night'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('honorific', models.CharField(max_length=25)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=500)),
                ('zip_code', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('notes', models.TextField(max_length=500)),
                ('card_holder_name', models.CharField(max_length=100)),
                ('credit_card_number', models.CharField(max_length=100)),
                ('expiry_month', models.CharField(max_length=100)),
                ('expiry_year', models.CharField(max_length=100)),
                ('cvv', models.CharField(max_length=100)),
                ('check_in', models.CharField(max_length=50)),
                ('check_out', models.CharField(max_length=50)),
                ('room', models.CharField(max_length=100)),
                ('room_id', models.CharField(max_length=100)),
                ('adult', models.CharField(max_length=20)),
                ('child', models.CharField(max_length=20)),
                ('no_of_guest', models.CharField(max_length=20)),
                ('no_of_nights', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('tax', models.CharField(max_length=20)),
                ('total_price', models.CharField(max_length=50)),
                ('term_condition', models.BooleanField(default=True)),
                ('user_id', models.IntegerField()),
                ('extra_services', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'be_booking_information',
            },
        ),
        migrations.CreateModel(
            name='ColorPalettes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_background_colour', models.CharField(max_length=100)),
                ('top_font_colour', models.CharField(max_length=100)),
                ('footer_background_colour', models.CharField(max_length=100)),
                ('footer_font_colour', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'be_color_palettes',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=500)),
                ('logo', models.ImageField(upload_to='be_property_logo')),
                ('copyright_name', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'be_contact_info',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('type', models.CharField(max_length=100)),
                ('coupon_amount', models.CharField(max_length=200, null=True)),
                ('active', models.BooleanField()),
                ('rooms', models.CharField(max_length=2000)),
                ('user_id', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'be_coupon',
            },
        ),
        migrations.CreateModel(
            name='ExtraService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('user_id', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'be_extra_services',
            },
        ),
        migrations.CreateModel(
            name='FooterWidgets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('user_id', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'be_widgets',
            },
        ),
        migrations.CreateModel(
            name='RoomAdditionalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_time', models.CharField(max_length=100)),
                ('checkout_time', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'be_room_additional_details',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(blank=True, max_length=200, null=True)),
                ('twitter', models.CharField(blank=True, max_length=200, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=200, null=True)),
                ('instagram', models.CharField(blank=True, max_length=200, null=True)),
                ('youtube', models.CharField(blank=True, max_length=200, null=True)),
                ('user_id', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'be_social_media',
            },
        ),
        migrations.CreateModel(
            name='TermCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=5000)),
                ('user_id', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'be_term&condition',
            },
        ),
        migrations.AlterField(
            model_name='bookingroom',
            name='description',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
